# Generated by Django 5.1.1 on 2024-09-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='extract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='movie',
            name='href',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.URLField(default='https://example.com/placeholder.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
