# Generated by Django 5.1.1 on 2024-09-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_movie_description_remove_movie_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
