# Generated by Django 5.1.1 on 2024-09-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ban_banned_by_alter_ban_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='banappeal',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
